installer: Install kbd package
dappnode/DAppNode pull request #583
Opened 2023-06-22 16:52 UTC by tolbrino

A missing `openvt` can lead to the script to fail.

2023-06-22 17:00 UTC, Teebor-Choka approved these changes
This should fix the failed installations on some machines.

2023-06-26 05:53 UTC, tolbrino commented
@dapplion @tropicar Anything I can do to help get this merged?

2023-06-26 07:40 UTC, pablomendezroyo commented
Hey! could you better describe whats the main purpose this package to be installed?

2023-06-26 07:43 UTC, tolbrino commented
> Hey! could you better describe whats the main purpose this package to be installed?

Installing the package is a safety measure to ensure the `openvt` binary is present, thus the script would not crash. The `openvt` binary is part of `kdb`. See https://packages.debian.org/bookworm/amd64/kbd/filelist

2023-06-26 07:47 UTC, pablomendezroyo commented
Do you need it during the ISO or script installation

2023-06-26 07:50 UTC, tolbrino commented
> Do you need it during the ISO or script installation method?

I believe we saw issues during ISO installation.

2023-06-26 08:08 UTC, pablomendezroyo requested changes

2023-06-26 08:08 UTC, pablomendezroyo commented on scripts/dappnode_install.sh
> +    apt-get install -y kbd
Please rewrite it to
```bash
# ensure openvt is installed prior to using it, openvt is a utility that is part of the kbd package.
apt-get update && apt-get install -y kbd
```

2023-06-26 09:27 UTC, tolbrino commented on scripts/dappnode_install.sh
> +    apt-get install -y kbd
done

2023-06-26 09:57 UTC, pablomendezroyo approved these changes

2023-06-26 09:57 UTC, merged

2023-06-26 10:24 UTC, pablomendezroyo commented
@tolbrino you will find the ISO with the changes at https://github.com/dappnode/DAppNode/releases/tag/v0.2.73?notification_referrer_id=NT_kwDOAny1iLM2ODc3OTg3MzAwOjQxNzI3MzY4

let us know how it goes